AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Golf Canada Dashboard API Gateway Proxy
  This SAM template creates an HTTP API Gateway that proxies requests to the
  Golf Canada API to get around CORS restrictions.

Parameters:
  TargetUrl:
    Type: String
    Description: The target URL to proxy requests to
    Default: https://scg.golfcanada.ca

Resources:
  ProxyApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: golf-canada-proxy
      ProtocolType: HTTP
      CorsConfiguration:
        AllowOrigins:
          - http://localhost:3000
          - http://localhost:5173
          - https://kenjdavidson.com
          - https://www.kenjdavidson.com
        AllowMethods:
          - OPTIONS
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
          - HEAD
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowCredentials: true
        MaxAge: 300

  ProxyIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ProxyApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Ref TargetUrl
      IntegrationMethod: ANY
      PayloadFormatVersion: "1.0"

  ProxyRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ProxyApi
      RouteKey: 'ANY /{proxy+}'
      Target: !Sub 'integrations/${ProxyIntegration}'

  ProxyStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ProxyApi
      StageName: prod
      AutoDeploy: true

Outputs:
  ApiEndpoint:
    Description: API Gateway Proxy Endpoint URL
    Value: !Sub "https://${ProxyApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
